### ISSUE TITLE
2d_mot and aion_source freeze on macOS with Metal Backend

### ISSUE THREAD

**Issue by SJSeckmeyer** [TeamAtomECS/AtomECSDemos#1]
Hi!

I tried running the demos on my local machine but unfortunately the demos "2d_mot" and "aion_source" freeze in debug and release mode after about 1-2 seconds. In debug mode they progress a little less far in terms of particle movement, probably because they run slower.
Since there is no crash I am unsure into which system to look for debugging.
The two demos that freeze both have blue particles while the working demos have red particles. Bu I do not know if this is just a coincidence.
If I remove the `create_atoms` system it works but that does not really say that much since then all other systems do not really run either.

The demos "3d_mot" and "top_trap" seem to run fine. And the three published demos on the website also work great.

Do you have any hints on how to gather more useful debug information like a "verbose" mode?
Or do you have tips how I reduce one of the examples to a more minimal system?
Please let me know if you need any more information in case you want to debug this.

My System:
- MacBook Pro 2020 (Intel Prozessor)
- `bevy_render::renderer: AdapterInfo { name: "Intel(R) Iris(TM) Plus Graphics", vendor: 0, device: 0, device_type: IntegratedGpu, backend: Metal }`
- rustc 1.60
- macOS 12.3.1 (current at time of writing)

**Comment by ElliotB256** [comment]
> I tried running the demos on my local machine but unfortunately the demos "2d_mot" and "aion_source" freeze in debug and release mode after about 1-2 seconds. In debug mode they progress a little less far in terms of particle movement, probably because they run slower.

I wonder if this suggests something like a memory leak in the rendering side. In that regard:
> reduce one of the examples to a more minimal system?
Could you try reducing the number of particles in the demo examples? Does the slowdown occur more gracefully for a lower particle number (might suggest a per-particle resource is leaking, so that the performance takes longer to drag).

Comparing the two setups at the start:
**3D MOT**:
```
    let mut app = App::new();
    app.add_plugin(atomecs::integrator::IntegrationPlugin);
    app.add_plugin(atomecs::initiate::InitiatePlugin);
    app.add_plugin(atomecs::magnetic::MagneticsPlugin);
    app.add_plugin(LaserPlugin::<{BEAM_NUMBER}>);
    app.add_plugin(LaserCoolingPlugin::<Rubidium87_780D2, {BEAM_NUMBER}>::default());
    app.add_plugin(BevyAtomECSPlugin);
    app.add_system(add_meshes_to_atoms::<Rubidium87_780D2>);
    app.add_system(atomecs::output::console_output::console_output);
    app.add_plugins(DefaultPlugins);
    app.add_system(atomecs::bevy_bridge::copy_positions);
    app.add_startup_system(setup_world);
    app.add_startup_system(create_atoms);
    app.add_startup_system(setup_camera);
    app.add_startup_system(add_atomecs_watermark);
    app.insert_resource(atomecs::bevy_bridge::Scale { 0: 1e3 });
    app.insert_resource(Timestep { delta: 2.0e-5 });
    app.insert_resource(EmissionForceOption::On(EmissionForceConfiguration {
        explicit_threshold: 5,
    }));
    app.insert_resource(ScatteringFluctuationsOption::On);
    //app.add_system(atomecs_demos::atoms::update_emissive_color::<Rubidium87_780D2>.after(atomecs::laser_cooling::LaserCoolingSystems::CalculateActualPhotonsScattered));
    app.run();
```

**2D MOT**
```
    let mut app = App::new();
    app.add_plugin(atomecs::integrator::IntegrationPlugin);
    app.add_plugin(atomecs::initiate::InitiatePlugin);
    app.add_plugin(atomecs::magnetic::MagneticsPlugin);
    app.add_plugin(LaserPlugin::<{BEAM_NUMBER}>);
    app.add_plugin(LaserCoolingPlugin::<Strontium88_461, {BEAM_NUMBER}>::default());
    app.add_plugin(SimulationRegionPlugin);
    app.add_plugin(BevyAtomECSPlugin);
    app.add_system(atomecs::output::console_output::console_output);
    app.add_plugins(DefaultPlugins);
    app.add_system(atomecs::bevy_bridge::copy_positions);
    app.add_system(add_meshes_to_atoms::<Strontium88_461>);
    app.add_startup_system(setup_world);
    app.add_system(create_atoms);
    app.add_startup_system(setup_camera);
    app.add_startup_system(add_atomecs_watermark);
    app.insert_resource(atomecs::bevy_bridge::Scale { 0: 7e1 });
    app.insert_resource(Timestep { delta: 2.0e-5 });
    app.insert_resource(EmissionForceOption::On(EmissionForceConfiguration {
        explicit_threshold: 5,
    }));
    app.insert_resource(ScatteringFluctuationsOption::On);
    app.run();
```

The notable differences are:
*  `app.add_plugin(SimulationRegionPlugin)` is used for 2d and aion
* Both aion source and 2d mot run add a small number of atoms each frame. If instead you change the system to a startup system and create a similar number of atoms as are in the Rb demo (but also only once, at the start of the simulation) does that prevent the slowdown? If adding atoms causes slowdown, it may suggest a resource not being freed by entity insertion or for newly created atoms.

**Comment by SJSeckmeyer** [comment]
Removing the `SimulationRegionPlugin` does not have any discernible effect. 
Changing the particle creation to a startup system also does not change anything.

The number of steps the simulation manages to do before stopping varies greatly. Sometimes it freezes after 3 steps, in other runs it manages to do over a hundred steps.
I have the impression that adding print commands for deugging tends to increase the number of steps before it freezes.
Is this maybe some kind of dead-lock issue? Are there any tools in bevy to debug that?

**Comment by ElliotB256** [comment]
If you disable the systems that add meshes to atoms/lasers and load the CAD, does it lockup then? It would be interesting to know if the bug is on the rendering or the AtomECS side

**Comment by SJSeckmeyer** [comment]
In all my tests this does not stop:
```rust
    let mut app = App::new();
    app.add_plugin(atomecs::integrator::IntegrationPlugin);
    app.add_plugin(atomecs::initiate::InitiatePlugin);
    app.add_plugin(atomecs::magnetic::MagneticsPlugin);
    app.add_plugin(LaserPlugin::<{BEAM_NUMBER}>);
    app.add_plugin(LaserCoolingPlugin::<Strontium88_461, {BEAM_NUMBER}>::default());
    // app.add_plugin(SimulationRegionPlugin);
    app.add_plugin(BevyAtomECSPlugin);
    app.add_system(console_output);
    app.add_plugins(DefaultPlugins);
    // app.add_system(atomecs::bevy_bridge::copy_positions);
    // app.add_system(add_meshes_to_atoms::<Strontium88_461>);
    // app.add_startup_system(setup_world);
    app.add_system(create_atoms);
    // app.add_startup_system(setup_camera);
    // app.add_startup_system(add_atomecs_watermark);
    app.insert_resource(atomecs::bevy_bridge::Scale { 0: 7e1 });
    app.insert_resource(Timestep { delta: 2.0e-5 });
    app.insert_resource(EmissionForceOption::On(EmissionForceConfiguration {
        explicit_threshold: 5,
    }));
    app.insert_resource(ScatteringFluctuationsOption::On);
    app.run();
}
```

But enabling either `SimulationRegionPlugin` or the other five rendering plugins causes the simulation to randomly get stuck. So this seems to be some interaction between the two groups.

Please note that I replaced the console_output system with this one for better debugging:
```rust
use atomecs::integrator::{Step};
/// A system that writes diagnostic output to the console window.
pub fn console_output(
    step: Res<Step>,
    query: Query<&Atom>
) {
    let atom_number = query.iter().count();
    println!("Step {}: simulating {} atoms.", step.n, atom_number);
}
```

**Comment by ElliotB256** [comment]
The `SimulationRegionPlugin` is responsible for deleting atoms that leave the simulation bounds. Perhaps in some cases it is trying to delete atoms in the same frame that one of the rendering plugins tries to make changes to them? The most likely candidate would be compositional changes (e.g. adding mesh components) that occur for deleted entities. Could you please try adding the rendering systems via `.add_system_to_stage(CoreStage::PostUpdate, ...)`, and see if that fixes it?

**Comment by SJSeckmeyer** [comment]
I changed `main` to the code below but it still locks up. Might be that it is a bit less but there is too much variance to say for sure.
Was that the change you meant or did I overlook something?
```rust
fn main() {

    let mut app = App::new();
    app.add_plugin(atomecs::integrator::IntegrationPlugin);
    app.add_plugin(atomecs::initiate::InitiatePlugin);
    app.add_plugin(atomecs::magnetic::MagneticsPlugin);
    app.add_plugin(LaserPlugin::<{BEAM_NUMBER}>);
    app.add_plugin(LaserCoolingPlugin::<Strontium88_461, {BEAM_NUMBER}>::default());
    app.add_plugin(SimulationRegionPlugin);
    app.add_plugin(BevyAtomECSPlugin);
    app.add_system(console_output);
    app.add_plugins(DefaultPlugins);
    app.add_system_to_stage(CoreStage::PostUpdate,atomecs::bevy_bridge::copy_positions);
    app.add_system_to_stage(CoreStage::PostUpdate,add_meshes_to_atoms::<Strontium88_461>);
    app.add_startup_system(setup_world);
    app.add_system(create_atoms);
    app.add_startup_system(setup_camera);
    app.add_startup_system(add_atomecs_watermark);
    app.insert_resource(atomecs::bevy_bridge::Scale { 0: 7e1 });
    app.insert_resource(Timestep { delta: 2.0e-5 });
    app.insert_resource(EmissionForceOption::On(EmissionForceConfiguration {
        explicit_threshold: 5,
    }));
    app.insert_resource(ScatteringFluctuationsOption::On);
    app.run();
}
```

**Comment by ElliotB256** [comment]
Interesting, if the freeze occurs when only the `SimulationRegionPlugin` is attached then it may indicate that we need to be more careful about when we delete them. For instance, if a filter is added to not delete newly created atoms at https://github.com/TeamAtomECS/AtomECS/blob/bevy/src/sim_region.rs#L59,
from `mut atom_query: Query<(&mut RegionTest, &Position)>,` to `mut atom_query: Query<(&mut RegionTest, &Position), Without<NewlyCreated>>,`

**Comment by ElliotB256** [comment]
(I'm assuming here that one possible cause could be trying to affect structural changes on entities that have been deleted. For instance, if various systems try to attach a component to a `NewlyCreated` atom on the first frame, but if it is also deleted in that same frame. The variable time to freeze would be just however long it takes to randomly spawn an atom outside the simulation region, given variance of the new atom random positions, etc. This _should_ panic, but maybe a bevy specific bug just causes a lock in this case?)

**Comment by SJSeckmeyer** [comment]
I now really start to make tables to keep track of the different combinations. I am close to writing a watchdog-script that automates that in order to rule out human error in the experiments.
I cannot find that the filter option changes anything but found by accident, that adding the `copy_positions` and `add_meshes_to_atoms` to the `PostUpdate` stage fixes hanging _wihout_ the `SimulationRegion`. (The difference between case 6 and 2).
So maybe we have multiple races in here and the `PostUpdate` stage fixed one of them.

My latest tests:
| ID | `add_meshes_to_atoms`, `copy_position`  | `SimulatorRegionPlugin` | 'Filter Patch`  | `setup_world`, `setup_camera`, `add_watermark` | works |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| 0 | system  | yes  | yes  | yes | no |
| 1 | system  | no  | yes  | yes | no |
| 2 | system  | no  | no  | yes | no |
| 3 | system  | no  | yes  | no | no |
| 4 | system_to_stage  | yes  | yes  | yes | no |
| 5 | system_to_stage  | no  | yes  | yes | yes |
| 6 | system_to_stage  | no  | no  | yes | yes |
| 7 | off  | yes  | no  | no | no |
| 8 | off  | yes  | yes  | no | no |
| 9 | off  | no  | yes  | no | yes |

So it seems that the `SimulatorRegionPlugin` still causes a hang somwhere.

**Comment by ElliotB256** [comment]
I've rebuilt these for the newly released bevy 0.8 - did that fix it for you?

**Comment by SJSeckmeyer** [comment]
Sorry for the late reply (I was on holidays).

Unfortunately the updated code does not fix it for me. I switched to Apple Silicon but that did not change the behavior of the old 0.7 version so I assume this is something that is triggered by something in macOS.

I narrowed down the init of 2d_mot.rs to the minimal example with which I can reproduce the hang:
```rust
let mut app = App::new();
app.add_plugin(atomecs::integrator::IntegrationPlugin);
app.add_plugin(atomecs::magnetic::MagneticsPlugin);
app.add_plugin(LaserPlugin::<{BEAM_NUMBER}>);
app.add_plugin(LaserCoolingPlugin::<Strontium88_461, {BEAM_NUMBER}>::default());
app.add_plugin(SimulationRegionPlugin);
app.add_plugins(DefaultPlugins);
app.add_startup_system(create_atoms);
app.run();
```

This is always complicated a bit by the fact that the hang is non-deterministic so there is always the possibility that the hang just has not happened yet.

I did an analysis of the remaining systems with [bevy_mod_debugdump](https://crates.io/crates/bevy_mod_debugdump):
![Screen Shot 2022-08-18 at 07 31 24-fullpage](https://user-images.githubusercontent.com/105303792/185301516-9f6faaf1-8291-43e8-a89d-ec8ff9d7afcd.png)

Unfortunately it is still a bit of a needle in a haystack for me about what systems could interfere.
If multiple stages would have a straight-forward "aliasing xor mutable violation" that would be prevented by bevy, right?

**Comment by SJSeckmeyer** [comment]
Looking at the call-stacks when attaching a debugger allowed me to reduce the deadlock to a pure bevy issue which I filed under [https://github.com/bevyengine/bevy/issues/5743](https://github.com/bevyengine/bevy/issues/5743)

**Comment by ElliotB256** [comment]
I noticed there was significant reworking of the ECS scheduler in bevy 0.9, so I plan to update the atomecs `bevy` branch to 0.9 and then we can see if this issue resolved itself. My work has been a little slowed since leaving academia, but I'm still intending to port more features over to the bevy branch and eventually make that main - the syntax and scheduler are pretty good now.

**Comment by ElliotB256** [comment]
I've pushed the update now and it should be running on bevy 0.9 - still get the error @SJSeckmeyer ?

**Comment by SJSeckmeyer** [comment]
I rechecked the old code with macOS 13.2 and Rust 1.67 with which it still hung and the new code fixes the hangs.
Now all five examples run through beautifully.
Thank you for fixing that!

**Comment by ElliotB256** [comment]
No problem, glad to hear it works for you now!
